version: '3'
services:
  nextjs:
    build: ./
    restart: always
    ports:
      - 3000:3000
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  node:
    image: testcab/cors-anywhere
    restart: always
    ports:
      - 8080:8080
